image: node:9.11-jessie

before_script:
  - npm install

cache:
    paths:
    - node_modules/

#services:
#  - mongo:3.2-jessie

#job_test:
#  stage: test
#  script:
#    - npm test
  
#job_build:
#  stage: build
#  script:
#    - npm run build
    
job_build_docker:
  tags:
    - bnf 
    - docker 
    - deploy
  script:
    - docker build -t discover .
    - docker run discover
# tr