# https://docs.gitlab.com/ce/ci/yaml/README.html

stages:
  - deploy
  
services:
 - docker:dind



# Deploy stage
deploy_semantic-paths:
  tags:
   - docker
  stage: deploy
  variables:
    DOCKER_TLS_VERIFY: 1
    DOCKER_HOST: tcp://129.175.22.62:2376
    DOCKER_MACHINE_NAME: default
  image: docker:latest
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.inria.fr
    - mkdir -p ~/.docker
    - echo "$TLSCACERT" > ~/.docker/ca.pem
    - echo "$TLSCERT" > ~/.docker/cert.pem
    - echo "$TLSKEY" > ~/.docker/key.pem
    - docker stack deploy semanticStack --compose-file docker-compose.yml
  only:
    - master
  when: manual