# https://docs.gitlab.com/ce/ci/yaml/README.html

stages:
  - build
  - test
  - deploy

# Environment templates
# -> Describe common environments to run stages

.node: &node
  image: node:9
  before_script:
    - npm install
  script: npm run $CI_JOB_STAGE
  # This folder is cached between builds
  # https://docs.gitlab.com/ce/ci/yaml/README.html#cache
  cache:
    paths:
      - node_modules/

# Build stage
# -> Run script to build any artifact needed by the application

Assets:
  <<: *node
  stage: build
  artifacts:
    paths:
      - public

# Test stage
# -> Run each independent test script in parallel

UT:
  <<: *node
  stage: test

#E2E:
#  <<: *node
#  stage: test
#  script: npm run e2e

# Deploy stage
# -> Automate deployment and may provide continuous deployment

#Production:
#  <<: *node
#  when: manual
#  environment:
#    name: production
#    url: https://example.com
