# https://docs.gitlab.com/ce/ci/yaml/README.html

stages:
  - test
  - build
  - deploy
  
services:
  - docker:dind

# Environment templates
# -> Describe common environments to run stages

.node: &node
  image: node
  tags:
    - node
  before_script:
    - npm install
  script: npm run $CI_JOB_STAGE
  # This folder is cached between builds
  # https://docs.gitlab.com/ce/ci/yaml/README.html#cache
  cache:
    paths:
      - node_modules/

# Test stage
UT:
  <<: *node
  stage: test

# Build stage
Assets:
  <<: *node
  stage: build

Docker:
  tags:
   - docker
  stage: build
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.inria.fr
    - docker build -t registry.gitlab.inria.fr/mdestand/semantic-paths .
    - docker push registry.gitlab.inria.fr/mdestand/semantic-paths
  only:
    - master


# Deploy stage
Production:
  tags:
   - docker
  stage: deploy
  variables:
    DOCKER_TLS_VERIFY: 1
    DOCKER_HOST: tcp://129.175.22.62:2376
    DOCKER_MACHINE_NAME: default
  image: docker:latest
  script:
    - mkdir -pv ~/.docker
    - echo "$TLSCACERT" > ~/.docker/ca.pem
    - echo "$TLSCERT" > ~/.docker/cert.pem
    - echo "$TLSKEY" > ~/.docker/key.pem
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.inria.fr
    - docker stack deploy --compose-file docker-compose.yml --with-registry-auth semanticStack
    # - docker service update  --with-registry-auth semanticStack_semanticpaths
  only:
    - master
  when: manual
