version: "3.5"
services:
  mongo:
    image: mongo:3.7
    container_name: semantic-paths_mongo
    restart: on-failure
    ports:
     - "27017:27107"
    network_mode: "host"
  semanticpaths:
    image: registry.gitlab.inria.fr/mdestand/semantic-paths:latest
    container_name: semantic-paths_server
#    command: ["npm", "start"]
    environment:
     - NODE_ENV="production"
    ports:
     - "5000:5000"
    depends_on:
     - "mongo"
    network_mode: "host"