version: "3.5"
services:
  virtuoso:
    image: tenforce/virtuoso:1.3.1-virtuoso7.2.2
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://ilda.nobel.fr"
    volumes:
      - db-virtuoso:/data
    ports:
      - 8890:8890
      - 1111:1111
  mongo:
    image: mongo:3.6
    env_file:
     - .env.dev
    ports:
     - 27017:27017
    volumes:
     - db-mongo:/data/db
  semanticpaths:
    build:
      context: ./
      dockerfile: Dockerfile-dev
    restart: always
    env_file:
     - .env.dev
    ports:
     - 80:80
     - 8081:8081
    depends_on:
     - mongo
     - virtuoso
    links:
     - virtuoso
     - mongo
volumes:
  db-mongo:
  db-virtuoso: