version: "3.5"
services:
  virtuoso:
    image: registry.gitlab.inria.fr/mdestand/virtuoso
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://ilda.nobel.fr"
    volumes:
      - ./db/virtuoso:/data
    ports:
      - 8890:8890
      - 1111:1111
  mongo:
    image: registry.gitlab.inria.fr/mdestand/mongo
    env_file:
     - .env.prod
    ports:
     - 27017:27017
    volumes:
     - ./db/mongo:/data/db
  semanticpaths:
    image: registry.gitlab.inria.fr/mdestand/semantic-paths
    env_file:
     - .env.prod
    ports:
     - 80:5000
    depends_on:
     - mongo
     - virtuoso
    links:
     - virtuoso
     - mongo
