version: "3.5"
services:
  virtuoso:
    image: openlink/virtuoso_opensource
    volumes:
      - db-virtuoso:/opt/virtuoso-opensource/database
    ports:
      - 8890:8890
      - 1111:1111
  mongo:
    image: mongo
    env_file:
      - .env
    ports:
      - 27017:27017
    volumes:
      - db-mongo:/data/db
  s-paths:
    image: registry.gitlab.inria.fr/mdestand/semantic-paths:latest
    build:
      context: ./
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    restart: always
    env_file:
      - .env
    ports:
      - 80:80
    depends_on:
      - virtuoso
      - mongo
    links:
      - virtuoso
      - mongo
volumes:
  db-virtuoso:
  db-mongo:
