version: "3.5"
services:
  virtuoso:
    image: openlink/virtuoso_opensource:latest
    volumes:
      - db-virtuoso:/opt/virtuoso-opensource/database
      #- db-virtuosobnf:/opt/virtuoso-opensource/database
      - ./dump:/opt/virtuoso-opensource/vad
    ports:
      - 8890:8890
      - 1111:1111
  mongo:
    image: mongo
    env_file:
     - .env.dev
    ports:
     - 27017:27017
    volumes:
     - db-mongo:/data/db
  semanticpaths:
    build:
      context: ./
      dockerfile: Dockerfile-dev
      args:
      - http_proxy
      - https_proxy
      - no_proxy
    restart: always
    env_file:
     - .env.dev
    ports:
     - 80:80
     - 8081:8081
     - 9229:9229
    volumes:
     - ./src:/src/
    depends_on:
     - mongo
     - virtuoso
    links:
     - virtuoso
     - mongo
volumes:
  db-mongo:
  db-virtuoso:
