version: "3.5"
services:
  virtuoso:
    image: openlink/virtuoso_opensource
    volumes:
      - db-virtuoso:/opt/virtuoso-opensource/database
    ports:
      - 8890:8890
      - 1111:1111
  mongo:
    image: mongo
    env_file:
      - .env
    ports:
      - 27017:27017
    volumes:
      - db-mongo:/data/db
  s-paths:
    build:
      context: ./
      dockerfile: Dockerfile-dev
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    env_file:
      - .env
    ports:
      - 80:80
      - 8081:8081
      - 9229:9229
    volumes:
      - ./src:/src/
    depends_on:
      - virtuoso
      - mongo
    links:
      - virtuoso
      - mongo
volumes:
  db-virtuoso:
  db-mongo:
