version: "3.5"
services:
  virtuoso:
    image: openlink/virtuoso_opensource:latest
    volumes:
      - db-virtuoso:/opt/virtuoso-opensource/database
    ports:
      - 8890:8890
      - 1111:1111
  mongo:
    image: mongo
    env_file:
     - .env.prod
    ports:
     - 27017:27017
    volumes:
     - db-mongo:/data/db
  semanticpaths:
    image: registry.gitlab.inria.fr/mdestand/semantic-paths:latest
    build:
      context: ./
      args:
      - http_proxy
      - https_proxy
      - no_proxy
    restart: always
    env_file:
     - .env.prod
    ports:
     - 80:80
    depends_on:
     - mongo
     - virtuoso
    links:
     - virtuoso
     - mongo
volumes:
  db-mongo:
  db-virtuoso:
