version: "3.5"
services:
  mongo:
    image: mongo:3.6
    container_name: semantic-paths_mongo
    restart: always
    env_file:
     - ${ENV}.env
    ports:
     - 27017:37107
    volumes:
     - ./db/mongo:/data/db
  semanticpaths:
    image: registry.gitlab.inria.fr/mdestand/semantic-paths:latest
    container_name: semantic-paths_server
    env_file:
     - ${ENV}.env
    ports:
     - 5000:5000
     - 8081:8081
    depends_on:
     - mongo
    volumes:
     - /:/build
