version: "3.5"
services:
  virtuoso:
    image: openlink/virtuoso-opensource-7
    restart: always
    volumes:
      - db-virtuoso:/opt/virtuoso-opensource/database
    ports:
      - 8890:8890
      - 1111:1111
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - db-mongo:/data/db
  s-paths:
    build:
      context: ./
    restart: always
    env_file:
      - .env
    ports:
      - 80:80
    depends_on:
      - virtuoso
      - mongo
    links:
      - virtuoso
      - mongo
volumes:
  db-virtuoso:
  db-mongo:
