version: "3.5"
services:
  virtuoso:
    image: tenforce/virtuoso:1.3.1-virtuoso7.2.2
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://ilda.nobel.fr"
    volumes:
      - db-virtuoso:/data
      - /home/deployer/dumps:/usr/local/virtuoso-opensource/share/virtuoso/vad
    ports:
      - 8890:8890
      - 1111:1111
  mongo:
    image: mongo:3.6
    env_file:
     - .env.prod
    ports:
     - 27017:27017
    volumes:
     - db-mongo:/data/db
  semanticpaths:
    image: registry.gitlab.inria.fr/mdestand/semantic-paths:latest
    build:
      context: ./
      args:
      - http_proxy
      - https_proxy
      - no_proxy
    restart: always
    env_file:
     - .env.prod
    ports:
     - 80:80
    depends_on:
     - mongo
     - virtuoso
    links:
     - virtuoso
     - mongo
volumes:
  db-mongo:
  db-virtuoso: