// import 'bootstrap/dist/css/bootstrap.css'
import './legend.css'
import './main.css'
import './debug.css'
import './header.css'
import './history.css'
import './timeline.css'
import './heatmap.css'
import './axis.css'
import './coverage.css'
import './nav.css'
import './tooltip.css'
import './propSelector.css'
import './selection.css'
import './transition.css'
import './uriwheel.css'
